using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Input;
using WPFCookBook.Common;
using WPFCookBook.DataService;
using WPFCookBook.Entities;

namespace WPFCookBook.ViewModels.basics
{
    public class XamlFundamentalsViewModel : BindableBase
    {
        private readonly ApplicationDBContext _context = new ApplicationDBContext();
        private string testDoc = "<FlowDocument PagePadding=\"5,0,5,0\" AllowDrop=\"True\" "
                + "xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\">"
                + "<Paragraph>Text generated by app back-end</Paragraph></FlowDocument>";
        private WpfCourseSectionItem chapter = new WpfCourseSectionItem();

        public XamlFundamentalsViewModel()
        {
            SaveDocument = new SaveFlowDocCommand(this);
            chapter = _context.CourseSectionItems.SingleOrDefault(x => x.Subtitle.Contains("Jargon"));
        }

        public ICommand SaveDocument { get; set; }
        public WpfCourseSectionItem CurrentChapter { get { return chapter; } }
        public string DocumentXaml
        {
            get { return testDoc; }
            set {
                PersistTwoWayPropToDB(chapter.ID, value);

                SetProperty(ref testDoc, value);

                
            }
        }

        private void PersistTwoWayPropToDB(long ID, string val)
        {
            var res = _context.CourseSectionItems.SingleOrDefault(x => x.ID == ID);
            res.Content = val;
            _context.SaveChangesAsync();
        }
    }
}
