using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Input;
using WPFCookBook.Common;

namespace WPFCookBook.ViewModels.basics
{
    public class XamlFundamentalsViewModel : BindableBase
    {

        private string testDoc = "<FlowDocument PagePadding=\"5,0,5,0\" AllowDrop=\"True\" "
                + "xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\">"
                + "<Paragraph>Text generated by app back-end</Paragraph></FlowDocument>";

        public XamlFundamentalsViewModel()
        {
            SaveDocument = new SaveFlowDocCommand(this);
        }

        public ICommand SaveDocument { get; set; }
        public string DocumentXaml
        {
            get { return testDoc; }
            set {
                SetProperty(ref testDoc, value);
            }
        }
    }
}
