using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using WPFCookBook.Common;
using WPFCookBook.DataService;
using WPFCookBook.Entities;

namespace WPFCookBook.ViewModels.basics
{
    public class XamlFundamentalsViewModel : BindableBase
    {
        private readonly ApplicationDBContext _context = new ApplicationDBContext();
        private string testDoc = "<FlowDocument PagePadding=\"5,0,5,0\" AllowDrop=\"True\" "
                + "xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\">"
                + "<Paragraph>Text generated by app back-end</Paragraph></FlowDocument>";
        public ICommand SaveDocumentCommand { get; private set; }
        

        private WpfCourseSection section;

        public XamlFundamentalsViewModel()
        {
            TestCommand = new CommandTemplate<string>(onBtn);
            SaveDocumentCommand = new SaveFlowDocCommand(this);
            section = _context.CourseSections.Include("SectionTopics").SingleOrDefault(x => x.Title.Contains("XAML Fundamentals"));
        }

        public CommandTemplate<string> TestCommand { get; private set; }
        public List<WpfCourseSectionItem> TopicsList { get
            {
                var result = section.SectionTopics.ToList();
                return result;
            }
        }
        
        private void onBtn(string none)
        {
            MessageBox.Show("!!!!");
        }
        public string DocumentXaml
        {
            get { return testDoc; }
            set {
                SetProperty(ref testDoc, value);
            }
        }

        //private void PersistTwoWayPropToDB(long ID, string val)
        //{
        //    var res = _context.CourseSectionItems.SingleOrDefault(x => x.ID == ID);
        //    res.Content = val;
        //    _context.SaveChangesAsync();
        //}
    }
}
